
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 05 01:45:56 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 7;
  public static final int CONST = 13;
  public static final int GE = 43;
  public static final int CASE = 28;
  public static final int LPAREN = 16;
  public static final int SEMI = 6;
  public static final int CONTINUE = 22;
  public static final int MINUS = 35;
  public static final int FOR = 26;
  public static final int CHARACTER = 11;
  public static final int RPAREN = 17;
  public static final int AND = 33;
  public static final int LT = 44;
  public static final int OR = 32;
  public static final int BOOL = 12;
  public static final int COMMA = 5;
  public static final int INC = 30;
  public static final int DIV = 38;
  public static final int PLUS = 36;
  public static final int IF = 19;
  public static final int DOT = 46;
  public static final int LE = 45;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int RBRACKET = 8;
  public static final int EQUAL = 14;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int MUL = 37;
  public static final int MOD = 39;
  public static final int NUMBER = 10;
  public static final int BREAK = 21;
  public static final int IDENT = 9;
  public static final int VOID = 18;
  public static final int EQ = 40;
  public static final int SWITCH = 27;
  public static final int COLON = 29;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int ENUM = 15;
  public static final int READ = 24;
  public static final int RBRACE = 4;
  public static final int NE = 41;
  public static final int PROG = 2;
  public static final int QUESTION = 34;
  public static final int DEC = 31;
  public static final int GT = 42;
  public static final int LENGTH = 48;
  public static final int PRINT = 25;
}

